git clone https://github.com/Addepar/ember-widgets/ ember-widgets
git clone https://github.com/CMUI/CMUI cmui
git clone https://github.com/DHTMLX/react-widgets dhtmlx-react-widgets
git clone https://github.com/DevExpress/DevExtreme dev-extreme
git clone https://github.com/FamousArchives/widgets famous-widgets
git clone https://github.com/GeekyAnts/NativeBase/ geeky-native-base
git clone https://github.com/JetBrains/ring-ui/ ring-ui
git clone https://github.com/JosephusPaye/Keen-UI/ keen-ui
git clone https://github.com/JxLib/JxLib jxlib
git clone https://github.com/Lobos/react-ui/ lobos-react-ui
git clone https://github.com/StreamElements/widgets stream-widgets
git clone https://github.com/amazeui/amazeui-react/ amazeui-react
git clone https://github.com/box/box-ui-elements/ box-ui
git clone https://github.com/codaxy/cxjs cxjs
git clone https://github.com/dojo/widgets dojo-widgets
git clone https://github.com/fabric8-ui/ngx-widgets ngx-widgets
git clone https://github.com/flamejs/flame.js frame
git clone https://github.com/gvas/knockout-jqueryui knockout-jqueryui
git clone https://github.com/jagenjo/litegui.js litegui
git clone https://github.com/jquense/react-widgets jquense-react-widgets
git clone https://github.com/jquery/jquery-ui jquery-ui
git clone https://github.com/klarna/ui klarna-ui
git clone https://github.com/liftmodules/widgets liftmodules-widgets
git clone https://github.com/lonelydawn/Widgets lonely-widgets
git clone https://github.com/mumuy/widget mumuy-widget
git clone https://github.com/ozoneplatform/owf-framework ows-framework
git clone https://github.com/reactstrap/reactstrap reactstrap-widgets
git clone https://github.com/roemhildtg/cmv-widgets/ cmv-widgets
git clone https://github.com/saucytiger/livepipe-ui/ livepipe-ui
git clone https://github.com/seriousben/embeddable-react-widget embeddable-react-widgets
git clone https://github.com/shoutem/ui/ shoutem-ui
git clone https://github.com/skipjac/zendesk-widgets zendesk-widgets
git clone https://github.com/telerik/kendo-ui-core/ kendo-ui
git clone https://github.com/valor-software/ngx-bootstrap ngx-bootstrap
git clone https://github.com/visionmedia/uikit/ uikit
git clone https://github.com/weaveworks/ui-components weaveworks
git clone https://github.com/wijmo/Wijmo-Open wijmo
git clone https://github.com/wxsms/uiv/ uiv
git clone https://github.com/xotahal/react-native-material-ui react-material-ui
git clone https://github.com/youzan/vant/ vant
git clone https://github.com/zoltan-dulac/html5Forms.js zoltan-widgets
git clone https://github.com/rackerlabs/encore-ui rackerlabs
git clone https://github.com/XboxYan/xy-ui xy-ui
git clone https://github.com/cuke-ui/cuke-ui cuke-ui
git clone https://github.com/mercadolibre/chico mercadolibre-chico
git clone https://github.com/ConsenSys/rimble-ui rimble-ui
git clone https://github.com/appnexus/lucid lucid
git clone https://github.com/myheritage/UiZoo.js uizoo
git clone https://github.com/siddharthkp/react-ui react-ui
git clone https://github.com/mineral-ui/mineral-ui mineral-ui
git clone https://github.com/juijs/jui-ui jui-ui
git clone https://github.com/sumup-oss/circuit-ui circuit-ui
git clone https://github.com/pivotal-cf/pivotal-ui pivotal-ui
git clone https://github.com/yued-fe/lulu lulu
