cd box-ui; es6-plato -r -d ./report ./src/components; cd ../
cd circuit-ui/; es6-plato -r -d ./report ./src/components; cd ../
cd cmui/; es6-plato -r -d ./report ./src/js; cd ../
cd cmv-widgets/; es6-plato -r -d ./report ./widgets; cd ../
cd cuke-ui/; es6-plato -r -d ./report ./components; cd ../
cd dev-extreme/; es6-plato -r -d ./report ./js/ui; cd ../
cd dhtmlx-react-widgets/; es6-plato -r -d ./report ./src; cd ../
cd dojo-widgets/; es6-plato -r -d ./report ./src; cd ../
cd ember-widgets/; es6-plato -r -d ./report ./app/components; cd ../
cd famous-widgets/; es6-plato -r -d ./report ./; cd ../
cd frame/; es6-plato -r -d ./report ./views; cd ../
cd geeky-native-base/; es6-plato -r -d ./report ./src/basic; cd ../
cd jquense-react-widgets/; es6-plato -r -d ./report ./packages/react-widgets/src; cd ../
cd jquery-ui/; es6-plato -r -d ./report ./ui/widgets; cd ../
cd jui-ui/; es6-plato -r -d ./report ./src/components; cd ../
cd jxlib/; es6-plato -r -d ./report ./src/Source/jx; cd ../
cd keen-ui/; es6-plato -r -d ./report ./src; cd ../
cd kendo-ui/; es6-plato -r -d ./report ./src; cd  ../
cd klarna-ui/; es6-plato -r -d ./report ./klarna-ui
cd knockout-jqueryui/; es6-plato -r -d ./report ./src; cd ../
cd liftmodules-widgets/; es6-plato -r -d ./report ./src/main/resources/toserve; cd  ../
cd litegui/; es6-plato -r -d ./report ./src; cd  ../
cd livepipe-ui/; es6-plato -r -d ./report ./src; cd ../
cd lobos-react-ui/; es6-plato -r -d ./report ./src; cd ../
cd lonely-widgets/; es6-plato -r -d ./report ./; cd ../
cd lucid/; es6-plato -r -d ./report ./src/components; cd ../
cd lulu/; es6-plato -r -d ./report ./theme/modern/js/common/ui; cd ../
cd mercadolibre-chico/; es6-plato -r -d ./report ./src/ui/scripts; cd ../
cd mineral-ui/; es6-plato -r -d ./report ./src/library; cd ../
cd mumuy-widget/; es6-plato -r -d ./report ./; cd  ../
cd ngx-bootstrap/; es6-plato -r -d ./report ./src; cd ../
cd ngx-widgets/; es6-plato -r -d ./report ./src/app; cd ../
cd pivotal-ui/; es6-plato -r -d ./report ./src/react; cd ../
cd react-material-ui/; es6-plato -r -d ./report ./src; cd ../
cd react-ui/; es6-plato -r -d ./report ./packages/react-ui/src/components; cd ../
cd reactstrap-widgets/; es6-plato -r -d ./report ./src; cd ../
cd rimble-ui/; es6-plato -r -d ./report ./src; cd ../
cd ring-ui/; es6-plato -r -d ./report ./components; cd ../
cd shoutem-ui/; es6-plato -r -d ./report ./components; cd ../
cd stream-widgets/; es6-plato -r -d ./report ./; cd ../
cd uikit/; es6-plato -r -d ./report ./lib/components; cd ../
cd uiv/; es6-plato -r -d ./report ./src/components; cd ../
cd vant/; es6-plato -r -d ./report ./src; cd ../
cd weaveworks/; es6-plato -r -d ./report ./src/components; cd ../
cd wijmo/; es6-plato -r -d ./report ./wijmo; cd ../
cd xy-ui/; es6-plato -r -d ./report ./components; cd ../
cd zendesk-widgets/; es6-plato -r -d ./report ./; cd ../
cd zoltan-widgets/; es6-plato -r -d ./report ./shared/js; cd ../
cd amazeui-react/; es6-plato -r -d ./report ./src; cd ../
