cat amazeui-react/.git/config | grep url >> generate-list2.sh
cat box-ui/.git/config | grep url >> generate-list2.sh
cat circuit-ui/.git/config | grep url >> generate-list2.sh
cat cmui/.git/config | grep url >> generate-list2.sh
cat cmv-widgets/.git/config | grep url >> generate-list2.sh
cat cuke-ui/.git/config | grep url >> generate-list2.sh
cat cxjs/.git/config | grep url >> generate-list2.sh
cat dev-extreme/.git/config | grep url >> generate-list2.sh
cat dhtmlx-react-widgets/.git/config | grep url >> generate-list2.sh
cat dojo-widgets/.git/config | grep url >> generate-list2.sh
cat embeddable-react-widgets/.git/config | grep url >> generate-list2.sh
cat ember-widgets/.git/config | grep url >> generate-list2.sh
cat famous-widgets/.git/config | grep url >> generate-list2.sh
cat frame/.git/config | grep url >> generate-list2.sh
cat geeky-native-base/.git/config | grep url >> generate-list2.sh
cat jquense-react-widgets/.git/config | grep url >> generate-list2.sh
cat jquery-ui/.git/config | grep url >> generate-list2.sh
cat jui-ui/.git/config | grep url >> generate-list2.sh
cat jxlib/.git/config | grep url >> generate-list2.sh
cat keen-ui/.git/config | grep url >> generate-list2.sh
cat kendo-ui/.git/config | grep url >> generate-list2.sh
cat klarna-ui/.git/config | grep url >> generate-list2.sh
cat knockout-jqueryui/.git/config | grep url >> generate-list2.sh
cat liftmodules-widgets/.git/config | grep url >> generate-list2.sh
cat litegui/.git/config | grep url >> generate-list2.sh
cat livepipe-ui/.git/config | grep url >> generate-list2.sh
cat lobos-react-ui/.git/config | grep url >> generate-list2.sh
cat lonely-widgets/.git/config | grep url >> generate-list2.sh
cat lucid/.git/config | grep url >> generate-list2.sh
cat lulu/.git/config | grep url >> generate-list2.sh
cat mercadolibre-chico/.git/config | grep url >> generate-list2.sh
cat merge-data.js.git/config | grep url >> generate-list2.sh
cat mineral-ui/.git/config | grep url >> generate-list2.sh
cat mumuy-widget/.git/config | grep url >> generate-list2.sh
cat ngx-bootstrap/.git/config | grep url >> generate-list2.sh
cat ngx-widgets/.git/config | grep url >> generate-list2.sh
cat node_modules/.git/config | grep url >> generate-list2.sh
cat ows-framework/.git/config | grep url >> generate-list2.sh
cat package-lock.json.git/config | grep url >> generate-list2.sh
cat pivotal-ui/.git/config | grep url >> generate-list2.sh
cat rackerlabs/.git/config | grep url >> generate-list2.sh
cat react-material-ui/.git/config | grep url >> generate-list2.sh
cat react-ui/.git/config | grep url >> generate-list2.sh
cat reactstrap-widgets/.git/config | grep url >> generate-list2.sh
cat results/.git/config | grep url >> generate-list2.sh
cat rimble-ui/.git/config | grep url >> generate-list2.sh
cat ring-ui/.git/config | grep url >> generate-list2.sh
cat shoutem-ui/.git/config | grep url >> generate-list2.sh
cat stream-widgets/.git/config | grep url >> generate-list2.sh
cat uikit/.git/config | grep url >> generate-list2.sh
cat uiv/.git/config | grep url >> generate-list2.sh
cat uizoo/.git/config | grep url >> generate-list2.sh
cat vant/.git/config | grep url >> generate-list2.sh
cat weaveworks/.git/config | grep url >> generate-list2.sh
cat wijmo/.git/config | grep url >> generate-list2.sh
cat xy-ui/.git/config | grep url >> generate-list2.sh
cat zendesk-widgets/.git/config | grep url >> generate-list2.sh
cat zoltan-widgets/.git/config | grep url >> generate-list2.sh
